server:
  port: 8080

spring:
  application:
    name: travel-insurance-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_insurance_db
    username: root
    password: 1qaz2wsx

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

security:
  jwt:
    secret: travel-insurance-secret-key-must-be-long-enough-32chars
    expiration-seconds: 86400